name: instagram_app_ui
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.11.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
